[package]
name = "sory-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sory-core = { workspace = true }
sory-model-provider-info = { workspace = true }
sory-protocol = { workspace = true }
sory-utils-absolute-path = { workspace = true }

[dev-dependencies]
sory-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
