load("//:defs.bzl", "sory_rust_crate")

sory_rust_crate(
    name = "core-plugins",
    crate_name = "sory_core_plugins",
    compile_data = glob(
        include = ["**"],
        exclude = [
            "**/* *",
            "BUILD.bazel",
            "Cargo.toml",
        ],
        allow_empty = True,
    ),
)
