// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { soryErrorInfo } from "./soryErrorInfo";

export type TurnError = { message: string, soryErrorInfo: soryErrorInfo | null, additionalDetails: string | null, };
