use crate::bespoke_event_handling::apply_bespoke_event_handling;
use crate::bespoke_event_handling::maybe_emit_hook_prompt_item_completed;
use crate::command_exec::CommandExecManager;
use crate::command_exec::StartCommandExecParams;
use crate::config_manager::ConfigManager;
use crate::error_code::INPUT_TOO_LARGE_ERROR_CODE;
use crate::error_code::invalid_params;
use crate::models::supported_models;
use crate::outgoing_message::ConnectionId;
use crate::outgoing_message::ConnectionRequestId;
use crate::outgoing_message::OutgoingMessageSender;
use crate::outgoing_message::RequestContext;
use crate::outgoing_message::ThreadScopedOutgoingMessageSender;
use crate::skills_watcher::SkillsWatcher;
use crate::thread_status::ThreadWatchManager;
use crate::thread_status::resolve_thread_status;
use chrono::Duration as ChronoDuration;
use chrono::SecondsFormat;
use sory_analytics::AnalyticsEventsClient;
use sory_analytics::AnalyticsJsonRpcError;
use sory_analytics::InputError;
use sory_analytics::TurnSteerRequestError;
use sory_app_server_protocol::Account;
use sory_app_server_protocol::AccountLoginCompletedNotification;
use sory_app_server_protocol::AccountUpdatedNotification;
use sory_app_server_protocol::AddCreditsNudgeCreditType;
use sory_app_server_protocol::AddCreditsNudgeEmailStatus;
use sory_app_server_protocol::AppInfo;
use sory_app_server_protocol::AppListUpdatedNotification;
use sory_app_server_protocol::AppSummary;
use sory_app_server_protocol::AppsListParams;
use sory_app_server_protocol::AppsListResponse;
use sory_app_server_protocol::AskForApproval;
use sory_app_server_protocol::AuthMode;
use sory_app_server_protocol::CancelLoginAccountParams;
use sory_app_server_protocol::CancelLoginAccountResponse;
use sory_app_server_protocol::CancelLoginAccountStatus;
use sory_app_server_protocol::ClientInfo;
use sory_app_server_protocol::ClientRequest;
use sory_app_server_protocol::ClientResponsePayload;
use sory_app_server_protocol::SoryErrorInfo;
use sory_app_server_protocol::CollaborationModeListParams;
use sory_app_server_protocol::CollaborationModeListResponse;
use sory_app_server_protocol::CommandExecParams;
use sory_app_server_protocol::CommandExecResizeParams;
use sory_app_server_protocol::CommandExecTerminateParams;
use sory_app_server_protocol::CommandExecWriteParams;
use sory_app_server_protocol::ConfigWarningNotification;
use sory_app_server_protocol::ConversationGitInfo;
use sory_app_server_protocol::ConversationSummary;
use sory_app_server_protocol::DeprecationNoticeNotification;
use sory_app_server_protocol::DynamicToolSpec as ApiDynamicToolSpec;
use sory_app_server_protocol::EnvironmentAddParams;
use sory_app_server_protocol::EnvironmentAddResponse;
use sory_app_server_protocol::ExperimentalFeature as ApiExperimentalFeature;
use sory_app_server_protocol::ExperimentalFeatureListParams;
use sory_app_server_protocol::ExperimentalFeatureListResponse;
use sory_app_server_protocol::ExperimentalFeatureStage as ApiExperimentalFeatureStage;
use sory_app_server_protocol::FeedbackUploadParams;
use sory_app_server_protocol::FeedbackUploadResponse;
use sory_app_server_protocol::GetAccountParams;
use sory_app_server_protocol::GetAccountRateLimitsResponse;
use sory_app_server_protocol::GetAccountResponse;
use sory_app_server_protocol::GetAuthStatusParams;
use sory_app_server_protocol::GetAuthStatusResponse;
use sory_app_server_protocol::GetConversationSummaryParams;
use sory_app_server_protocol::GetConversationSummaryResponse;
use sory_app_server_protocol::GitDiffToRemoteParams;
use sory_app_server_protocol::GitDiffToRemoteResponse;
use sory_app_server_protocol::GitInfo as ApiGitInfo;
use sory_app_server_protocol::HookMetadata;
use sory_app_server_protocol::HooksListParams;
use sory_app_server_protocol::HooksListResponse;
use sory_app_server_protocol::InitializeParams;
use sory_app_server_protocol::InitializeResponse;
use sory_app_server_protocol::JSONRPCErrorError;
use sory_app_server_protocol::ListMcpServerStatusParams;
use sory_app_server_protocol::ListMcpServerStatusResponse;
use sory_app_server_protocol::LoginAccountParams;
use sory_app_server_protocol::LoginAccountResponse;
use sory_app_server_protocol::LoginApiKeyParams;
use sory_app_server_protocol::LogoutAccountResponse;
use sory_app_server_protocol::MarketplaceAddParams;
use sory_app_server_protocol::MarketplaceAddResponse;
use sory_app_server_protocol::MarketplaceInterface;
use sory_app_server_protocol::MarketplaceRemoveParams;
use sory_app_server_protocol::MarketplaceRemoveResponse;
use sory_app_server_protocol::MarketplaceUpgradeErrorInfo;
use sory_app_server_protocol::MarketplaceUpgradeParams;
use sory_app_server_protocol::MarketplaceUpgradeResponse;
use sory_app_server_protocol::McpResourceReadParams;
use sory_app_server_protocol::McpResourceReadResponse;
use sory_app_server_protocol::McpServerOauthLoginCompletedNotification;
use sory_app_server_protocol::McpServerOauthLoginParams;
use sory_app_server_protocol::McpServerOauthLoginResponse;
use sory_app_server_protocol::McpServerRefreshResponse;
use sory_app_server_protocol::McpServerStatus;
use sory_app_server_protocol::McpServerStatusDetail;
use sory_app_server_protocol::McpServerToolCallParams;
use sory_app_server_protocol::McpServerToolCallResponse;
use sory_app_server_protocol::MemoryResetResponse;
use sory_app_server_protocol::MockExperimentalMethodParams;
use sory_app_server_protocol::MockExperimentalMethodResponse;
use sory_app_server_protocol::ModelListParams;
use sory_app_server_protocol::ModelListResponse;
use sory_app_server_protocol::PermissionProfileSelectionParams;
use sory_app_server_protocol::PluginDetail;
use sory_app_server_protocol::PluginInstallParams;
use sory_app_server_protocol::PluginInstallResponse;
use sory_app_server_protocol::PluginInterface;
use sory_app_server_protocol::PluginListMarketplaceKind;
use sory_app_server_protocol::PluginListParams;
use sory_app_server_protocol::PluginListResponse;
use sory_app_server_protocol::PluginMarketplaceEntry;
use sory_app_server_protocol::PluginReadParams;
use sory_app_server_protocol::PluginReadResponse;
use sory_app_server_protocol::PluginShareCheckoutParams;
use sory_app_server_protocol::PluginShareCheckoutResponse;
use sory_app_server_protocol::PluginShareContext;
use sory_app_server_protocol::PluginShareDeleteParams;
use sory_app_server_protocol::PluginShareDeleteResponse;
use sory_app_server_protocol::PluginShareDiscoverability;
use sory_app_server_protocol::PluginShareListItem;
use sory_app_server_protocol::PluginShareListParams;
use sory_app_server_protocol::PluginShareListResponse;
use sory_app_server_protocol::PluginSharePrincipal;
use sory_app_server_protocol::PluginSharePrincipalType;
use sory_app_server_protocol::PluginShareSaveParams;
use sory_app_server_protocol::PluginShareSaveResponse;
use sory_app_server_protocol::PluginShareTarget;
use sory_app_server_protocol::PluginShareUpdateDiscoverability;
use sory_app_server_protocol::PluginShareUpdateTargetsParams;
use sory_app_server_protocol::PluginShareUpdateTargetsResponse;
use sory_app_server_protocol::PluginSkillReadParams;
use sory_app_server_protocol::PluginSkillReadResponse;
use sory_app_server_protocol::PluginSource;
use sory_app_server_protocol::PluginSummary;
use sory_app_server_protocol::PluginUninstallParams;
use sory_app_server_protocol::PluginUninstallResponse;
use sory_app_server_protocol::RequestId;
use sory_app_server_protocol::ReviewDelivery as ApiReviewDelivery;
use sory_app_server_protocol::ReviewStartParams;
use sory_app_server_protocol::ReviewStartResponse;
use sory_app_server_protocol::ReviewTarget as ApiReviewTarget;
use sory_app_server_protocol::SandboxMode;
use sory_app_server_protocol::SendAddCreditsNudgeEmailParams;
use sory_app_server_protocol::SendAddCreditsNudgeEmailResponse;
use sory_app_server_protocol::ServerNotification;
use sory_app_server_protocol::ServerRequestResolvedNotification;
use sory_app_server_protocol::SkillSummary;
use sory_app_server_protocol::SkillsConfigWriteParams;
use sory_app_server_protocol::SkillsConfigWriteResponse;
use sory_app_server_protocol::SkillsListParams;
use sory_app_server_protocol::SkillsListResponse;
use sory_app_server_protocol::SortDirection;
use sory_app_server_protocol::Thread;
use sory_app_server_protocol::ThreadApproveGuardianDeniedActionParams;
use sory_app_server_protocol::ThreadApproveGuardianDeniedActionResponse;
use sory_app_server_protocol::ThreadArchiveParams;
use sory_app_server_protocol::ThreadArchiveResponse;
use sory_app_server_protocol::ThreadArchivedNotification;
use sory_app_server_protocol::ThreadBackgroundTerminalsCleanParams;
use sory_app_server_protocol::ThreadBackgroundTerminalsCleanResponse;
use sory_app_server_protocol::ThreadClosedNotification;
use sory_app_server_protocol::ThreadCompactStartParams;
use sory_app_server_protocol::ThreadCompactStartResponse;
use sory_app_server_protocol::ThreadDecrementElicitationParams;
use sory_app_server_protocol::ThreadDecrementElicitationResponse;
use sory_app_server_protocol::ThreadForkParams;
use sory_app_server_protocol::ThreadForkResponse;
use sory_app_server_protocol::ThreadGoal;
use sory_app_server_protocol::ThreadGoalClearParams;
use sory_app_server_protocol::ThreadGoalClearResponse;
use sory_app_server_protocol::ThreadGoalClearedNotification;
use sory_app_server_protocol::ThreadGoalGetParams;
use sory_app_server_protocol::ThreadGoalGetResponse;
use sory_app_server_protocol::ThreadGoalSetParams;
use sory_app_server_protocol::ThreadGoalSetResponse;
use sory_app_server_protocol::ThreadGoalStatus;
use sory_app_server_protocol::ThreadGoalUpdatedNotification;
use sory_app_server_protocol::ThreadHistoryBuilder;
use sory_app_server_protocol::ThreadIncrementElicitationParams;
use sory_app_server_protocol::ThreadIncrementElicitationResponse;
use sory_app_server_protocol::ThreadInjectItemsParams;
use sory_app_server_protocol::ThreadInjectItemsResponse;
use sory_app_server_protocol::ThreadItem;
use sory_app_server_protocol::ThreadListCwdFilter;
use sory_app_server_protocol::ThreadListParams;
use sory_app_server_protocol::ThreadListResponse;
use sory_app_server_protocol::ThreadLoadedListParams;
use sory_app_server_protocol::ThreadLoadedListResponse;
use sory_app_server_protocol::ThreadMemoryModeSetParams;
use sory_app_server_protocol::ThreadMemoryModeSetResponse;
use sory_app_server_protocol::ThreadMetadataGitInfoUpdateParams;
use sory_app_server_protocol::ThreadMetadataUpdateParams;
use sory_app_server_protocol::ThreadMetadataUpdateResponse;
use sory_app_server_protocol::ThreadNameUpdatedNotification;
use sory_app_server_protocol::ThreadReadParams;
use sory_app_server_protocol::ThreadReadResponse;
use sory_app_server_protocol::ThreadRealtimeAppendAudioParams;
use sory_app_server_protocol::ThreadRealtimeAppendAudioResponse;
use sory_app_server_protocol::ThreadRealtimeAppendTextParams;
use sory_app_server_protocol::ThreadRealtimeAppendTextResponse;
use sory_app_server_protocol::ThreadRealtimeListVoicesResponse;
use sory_app_server_protocol::ThreadRealtimeStartParams;
use sory_app_server_protocol::ThreadRealtimeStartResponse;
use sory_app_server_protocol::ThreadRealtimeStartTransport;
use sory_app_server_protocol::ThreadRealtimeStopParams;
use sory_app_server_protocol::ThreadRealtimeStopResponse;
use sory_app_server_protocol::ThreadResumeParams;
use sory_app_server_protocol::ThreadResumeResponse;
use sory_app_server_protocol::ThreadRollbackParams;
use sory_app_server_protocol::ThreadSetNameParams;
use sory_app_server_protocol::ThreadSetNameResponse;
use sory_app_server_protocol::ThreadShellCommandParams;
use sory_app_server_protocol::ThreadShellCommandResponse;
use sory_app_server_protocol::ThreadSortKey;
use sory_app_server_protocol::ThreadSourceKind;
use sory_app_server_protocol::ThreadStartParams;
use sory_app_server_protocol::ThreadStartResponse;
use sory_app_server_protocol::ThreadStartedNotification;
use sory_app_server_protocol::ThreadStatus;
use sory_app_server_protocol::ThreadTurnsItemsListParams;
use sory_app_server_protocol::ThreadTurnsListParams;
use sory_app_server_protocol::ThreadTurnsListResponse;
use sory_app_server_protocol::ThreadUnarchiveParams;
use sory_app_server_protocol::ThreadUnarchiveResponse;
use sory_app_server_protocol::ThreadUnarchivedNotification;
use sory_app_server_protocol::ThreadUnsubscribeParams;
use sory_app_server_protocol::ThreadUnsubscribeResponse;
use sory_app_server_protocol::ThreadUnsubscribeStatus;
use sory_app_server_protocol::Turn;
use sory_app_server_protocol::TurnEnvironmentParams;
use sory_app_server_protocol::TurnError;
use sory_app_server_protocol::TurnInterruptParams;
use sory_app_server_protocol::TurnInterruptResponse;
use sory_app_server_protocol::TurnItemsView;
use sory_app_server_protocol::TurnStartParams;
use sory_app_server_protocol::TurnStartResponse;
use sory_app_server_protocol::TurnStatus;
use sory_app_server_protocol::TurnSteerParams;
use sory_app_server_protocol::TurnSteerResponse;
use sory_app_server_protocol::UserInput as V2UserInput;
use sory_app_server_protocol::WindowsSandboxReadiness;
use sory_app_server_protocol::WindowsSandboxReadinessResponse;
use sory_app_server_protocol::WindowsSandboxSetupCompletedNotification;
use sory_app_server_protocol::WindowsSandboxSetupMode;
use sory_app_server_protocol::WindowsSandboxSetupStartParams;
use sory_app_server_protocol::WindowsSandboxSetupStartResponse;
use sory_arg0::Arg0DispatchPaths;
use sory_backend_client::AddCreditsNudgeCreditType as BackendAddCreditsNudgeCreditType;
use sory_backend_client::Client as BackendClient;
use sory_chatgpt::connectors;
use sory_chatgpt::workspace_settings;
use sory_config::CloudRequirementsLoadError;
use sory_config::CloudRequirementsLoadErrorCode;
use sory_config::ConfigLayerStack;
use sory_config::loader::project_trust_key;
use sory_config::types::McpServerTransportConfig;
use sory_core::SoryThread;
use sory_core::SoryThreadTurnContextOverrides;
use sory_core::ExternalGoalPreviousStatus;
use sory_core::ExternalGoalSet;
use sory_core::ForkSnapshot;
use sory_core::NewThread;
#[cfg(test)]
use sory_core::SessionMeta;
use sory_core::StartThreadOptions;
use sory_core::SteerInputError;
use sory_core::ThreadConfigSnapshot;
use sory_core::ThreadManager;
use sory_core::config::Config;
use sory_core::config::ConfigOverrides;
use sory_core::config::NetworkProxyAuditMetadata;
use sory_core::config::edit::ConfigEdit;
use sory_core::config::edit::ConfigEditsBuilder;
use sory_core::exec::ExecCapturePolicy;
use sory_core::exec::ExecExpiration;
use sory_core::exec::ExecParams;
use sory_core::exec_env::create_env;
use sory_core::path_utils;
#[cfg(test)]
use sory_core::read_head_for_summary;
use sory_core::sandboxing::SandboxPermissions;
use sory_core::windows_sandbox::WindowsSandboxLevelExt;
use sory_core::windows_sandbox::WindowsSandboxSetupMode as CoreWindowsSandboxSetupMode;
use sory_core::windows_sandbox::WindowsSandboxSetupRequest;
use sory_core::windows_sandbox::sandbox_setup_is_complete;
use sory_core_plugins::OPENAI_CURATED_MARKETPLACE_NAME;
use sory_core_plugins::PluginInstallError as CorePluginInstallError;
use sory_core_plugins::PluginInstallRequest;
use sory_core_plugins::PluginLoadOutcome;
use sory_core_plugins::PluginReadRequest;
use sory_core_plugins::PluginUninstallError as CorePluginUninstallError;
use sory_core_plugins::loader::load_plugin_apps;
use sory_core_plugins::loader::load_plugin_mcp_servers;
use sory_core_plugins::loader::plugin_telemetry_metadata_from_root;
use sory_core_plugins::manifest::PluginManifestInterface;
use sory_core_plugins::marketplace::MarketplaceError;
use sory_core_plugins::marketplace::MarketplacePluginSource;
use sory_core_plugins::marketplace_add::MarketplaceAddError;
use sory_core_plugins::marketplace_add::MarketplaceAddRequest;
use sory_core_plugins::marketplace_add::add_marketplace as add_marketplace_to_sory_home;
use sory_core_plugins::marketplace_remove::MarketplaceRemoveError;
use sory_core_plugins::marketplace_remove::MarketplaceRemoveRequest as CoreMarketplaceRemoveRequest;
use sory_core_plugins::marketplace_remove::remove_marketplace;
use sory_core_plugins::remote::RemoteMarketplace;
use sory_core_plugins::remote::RemoteMarketplaceSource;
use sory_core_plugins::remote::RemotePluginCatalogError;
use sory_core_plugins::remote::RemotePluginDetail as RemoteCatalogPluginDetail;
use sory_core_plugins::remote::RemotePluginServiceConfig;
use sory_core_plugins::remote::RemotePluginShareContext as RemoteCatalogPluginShareContext;
use sory_core_plugins::remote::RemotePluginShareSummary as RemoteCatalogPluginShareSummary;
use sory_core_plugins::remote::RemotePluginSummary as RemoteCatalogPluginSummary;
use sory_exec_server::EnvironmentManager;
use sory_exec_server::LOCAL_FS;
use sory_features::FEATURES;
use sory_features::Feature;
use sory_features::Stage;
use sory_feedback::soryFeedback;
use sory_feedback::FeedbackAttachmentPath;
use sory_feedback::FeedbackUploadOptions;
use sory_git_utils::git_diff_to_remote;
use sory_git_utils::resolve_root_git_project_for_trust;
use sory_login::AuthManager;
use sory_login::CLIENT_ID;
use sory_login::soryAuth;
use sory_login::ServerOptions as LoginServerOptions;
use sory_login::ShutdownHandle;
use sory_login::auth::login_with_chatgpt_auth_tokens;
use sory_login::complete_device_code_login;
use sory_login::login_with_api_key;
use sory_login::request_device_code;
use sory_login::run_login_server;
use sory_mcp::McpRuntimeEnvironment;
use sory_mcp::McpServerStatusSnapshot;
use sory_mcp::McpSnapshotDetail;
use sory_mcp::collect_mcp_server_status_snapshot_with_detail;
use sory_mcp::discover_supported_scopes;
use sory_mcp::effective_mcp_servers;
use sory_mcp::read_mcp_resource as read_mcp_resource_without_thread;
use sory_mcp::resolve_oauth_scopes;
use sory_memories_write::clear_memory_roots_contents;
use sory_model_provider::ProviderAccountError;
use sory_model_provider::create_model_provider;
use sory_models_manager::collaboration_mode_presets::builtin_collaboration_mode_presets;
use sory_protocol::ThreadId;
use sory_protocol::config_types::CollaborationMode;
use sory_protocol::config_types::ForcedLoginMethod;
use sory_protocol::config_types::Personality;
use sory_protocol::config_types::TrustLevel;
use sory_protocol::config_types::WindowsSandboxLevel;
use sory_protocol::dynamic_tools::DynamicToolSpec as CoreDynamicToolSpec;
use sory_protocol::error::SoryErr;
use sory_protocol::error::Result as soryResult;
#[cfg(test)]
use sory_protocol::items::TurnItem;
use sory_protocol::models::ResponseItem;
#[cfg(test)]
use sory_protocol::permissions::FileSystemSandboxPolicy;
use sory_protocol::protocol::AgentStatus;
use sory_protocol::protocol::ConversationAudioParams;
use sory_protocol::protocol::ConversationStartParams;
use sory_protocol::protocol::ConversationStartTransport;
use sory_protocol::protocol::ConversationTextParams;
use sory_protocol::protocol::EventMsg;
#[cfg(test)]
use sory_protocol::protocol::GitInfo as CoreGitInfo;
use sory_protocol::protocol::InitialHistory;
use sory_protocol::protocol::McpAuthStatus as CoreMcpAuthStatus;
use sory_protocol::protocol::Op;
use sory_protocol::protocol::RateLimitSnapshot as CoreRateLimitSnapshot;
use sory_protocol::protocol::RealtimeVoicesList;
use sory_protocol::protocol::ResumedHistory;
use sory_protocol::protocol::ReviewDelivery as CoreReviewDelivery;
use sory_protocol::protocol::ReviewRequest;
use sory_protocol::protocol::ReviewTarget as CoreReviewTarget;
use sory_protocol::protocol::RolloutItem;
use sory_protocol::protocol::SessionConfiguredEvent;
#[cfg(test)]
use sory_protocol::protocol::SessionMetaLine;
use sory_protocol::protocol::TurnEnvironmentSelection;
use sory_protocol::protocol::USER_MESSAGE_BEGIN;
use sory_protocol::protocol::W3cTraceContext;
use sory_protocol::user_input::MAX_USER_INPUT_TEXT_CHARS;
use sory_protocol::user_input::UserInput as CoreInputItem;
use sory_rmcp_client::perform_oauth_login_return_url;
use sory_rollout::EventPersistenceMode;
use sory_rollout::is_persisted_rollout_item;
use sory_rollout::state_db::StateDbHandle;
use sory_rollout::state_db::reconcile_rollout;
use sory_state::ThreadMetadata;
use sory_state::log_db::LogDbLayer;
use sory_thread_store::ArchiveThreadParams as StoreArchiveThreadParams;
use sory_thread_store::GitInfoPatch as StoreGitInfoPatch;
use sory_thread_store::ListThreadsParams as StoreListThreadsParams;
use sory_thread_store::LocalThreadStore;
use sory_thread_store::ReadThreadByRolloutPathParams as StoreReadThreadByRolloutPathParams;
use sory_thread_store::ReadThreadParams as StoreReadThreadParams;
use sory_thread_store::SortDirection as StoreSortDirection;
use sory_thread_store::StoredThread;
use sory_thread_store::ThreadMetadataPatch as StoreThreadMetadataPatch;
use sory_thread_store::ThreadSortKey as StoreThreadSortKey;
use sory_thread_store::ThreadStore;
use sory_thread_store::ThreadStoreError;
use sory_utils_absolute_path::AbsolutePathBuf;
use sory_utils_pty::DEFAULT_OUTPUT_BYTES_CAP;
use std::collections::HashMap;
use std::collections::HashSet;
use std::io::Error as IoError;
use std::path::Path;
use std::path::PathBuf;
use std::result::Result;
use std::sync::Arc;
use std::time::Duration;
use std::time::Instant;
use tokio::sync::Mutex;
use tokio::sync::Semaphore;
use tokio::sync::SemaphorePermit;
use tokio::sync::broadcast;
use tokio::sync::oneshot;
use tokio::sync::watch;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use toml::Value as TomlValue;
use tracing::Instrument;
use tracing::error;
use tracing::info;
use tracing::warn;
use uuid::Uuid;

#[cfg(test)]
use sory_app_server_protocol::ServerRequest;

mod account_processor;
mod apps_processor;
mod catalog_processor;
mod command_exec_processor;
mod config_processor;
mod environment_processor;
mod external_agent_config_processor;
mod feedback_doctor_report;
mod feedback_processor;
mod fs_processor;
mod git_processor;
mod initialize_processor;
mod marketplace_processor;
mod mcp_processor;
mod plugins;
mod process_exec_processor;
mod remote_control_processor;
mod search;
mod thread_processor;
mod token_usage_replay;
mod turn_processor;
mod windows_sandbox_processor;

pub(crate) use account_processor::AccountRequestProcessor;
pub(crate) use apps_processor::AppsRequestProcessor;
pub(crate) use catalog_processor::CatalogRequestProcessor;
pub(crate) use command_exec_processor::CommandExecRequestProcessor;
pub(crate) use config_processor::ConfigRequestProcessor;
pub(crate) use environment_processor::EnvironmentRequestProcessor;
pub(crate) use external_agent_config_processor::ExternalAgentConfigRequestProcessor;
pub(crate) use feedback_processor::FeedbackRequestProcessor;
pub(crate) use fs_processor::FsRequestProcessor;
pub(crate) use git_processor::GitRequestProcessor;
pub(crate) use initialize_processor::InitializeRequestProcessor;
pub(crate) use marketplace_processor::MarketplaceRequestProcessor;
pub(crate) use mcp_processor::McpRequestProcessor;
pub(crate) use plugins::PluginRequestProcessor;
pub(crate) use process_exec_processor::ProcessExecRequestProcessor;
pub(crate) use remote_control_processor::RemoteControlRequestProcessor;
pub(crate) use search::SearchRequestProcessor;
pub(crate) use thread_goal_processor::ThreadGoalRequestProcessor;
pub(crate) use thread_processor::ThreadRequestProcessor;
pub(crate) use turn_processor::TurnRequestProcessor;
pub(crate) use windows_sandbox_processor::WindowsSandboxRequestProcessor;

use crate::error_code::internal_error;
use crate::error_code::invalid_request;
use crate::filters::compute_source_filters;
use crate::filters::source_kind_matches;
use crate::thread_state::ConnectionCapabilities;
use crate::thread_state::ThreadListenerCommand;
use crate::thread_state::ThreadState;
use crate::thread_state::ThreadStateManager;
use token_usage_replay::latest_token_usage_turn_id_from_rollout_items;
use token_usage_replay::send_thread_token_usage_update_to_connection;

mod config_errors;
mod request_errors;
mod thread_goal_processor;
mod thread_lifecycle;
mod thread_resume_redaction;
mod thread_summary;

use self::config_errors::*;
use self::request_errors::*;
use self::thread_goal_processor::api_thread_goal_from_state;
use self::thread_lifecycle::*;
use self::thread_resume_redaction::*;
use self::thread_summary::*;

pub(crate) use self::thread_lifecycle::populate_thread_turns_from_history;
pub(crate) use self::thread_processor::thread_from_stored_thread;
#[cfg(test)]
pub(crate) use self::thread_summary::read_summary_from_rollout;
#[cfg(test)]
pub(crate) use self::thread_summary::summary_to_thread;

pub(crate) fn build_api_turns_from_rollout_items(items: &[RolloutItem]) -> Vec<Turn> {
    let mut builder = ThreadHistoryBuilder::new();
    for item in items {
        if is_persisted_rollout_item(item, EventPersistenceMode::Limited) {
            builder.handle_rollout_item(item);
        }
    }
    builder.finish()
}
