[package]
edition.workspace = true
license.workspace = true
name = "sory-analytics"
version.workspace = true

[lib]
doctest = false
name = "sory_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
sory-app-server-protocol = { workspace = true }
sory-git-utils = { workspace = true }
sory-login = { workspace = true }
sory-model-provider = { workspace = true }
sory-plugin = { workspace = true }
sory-protocol = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
sory-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
