[package]
edition.workspace = true
license.workspace = true
name = "sory-core"
version.workspace = true

[lib]
name = "sory_core"
path = "src/lib.rs"

[[bin]]
name = "sory-write-config-schema"
path = "src/bin/config_schema.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-channel = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bm25 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
sory-analytics = { workspace = true }
sory-api = { workspace = true }
sory-app-server-protocol = { workspace = true }
sory-apply-patch = { workspace = true }
sory-async-utils = { workspace = true }
sory-code-mode = { workspace = true }
sory-connectors = { workspace = true }
sory-config = { workspace = true }
sory-core-plugins = { workspace = true }
sory-core-skills = { workspace = true }
sory-exec-server = { workspace = true }
sory-extension-api = { workspace = true }
sory-features = { workspace = true }
sory-feedback = { workspace = true }
sory-login = { workspace = true }
sory-memories-read = { workspace = true }
sory-mcp = { workspace = true }
sory-model-provider-info = { workspace = true }
sory-models-manager = { workspace = true }
sory-shell-command = { workspace = true }
sory-execpolicy = { workspace = true }
sory-git-utils = { workspace = true }
sory-hooks = { workspace = true }
sory-network-proxy = { workspace = true }
sory-otel = { workspace = true }
sory-plugin = { workspace = true }
sory-model-provider = { workspace = true }
sory-protocol = { workspace = true }
sory-response-debug-context = { workspace = true }
sory-rollout = { workspace = true }
sory-rollout-trace = { workspace = true }
sory-rmcp-client = { workspace = true }
sory-sandboxing = { workspace = true }
sory-state = { workspace = true }
sory-terminal-detection = { workspace = true }
sory-thread-store = { workspace = true }
sory-tools = { workspace = true }
sory-utils-absolute-path = { workspace = true }
sory-client = { workspace = true }
sory-utils-cache = { workspace = true }
sory-utils-image = { workspace = true }
sory-utils-home-dir = { workspace = true }
sory-utils-output-truncation = { workspace = true }
sory-utils-path = { workspace = true }
sory-utils-plugins = { workspace = true }
sory-utils-pty = { workspace = true }
sory-utils-string = { workspace = true }
sory-utils-stream-parser = { workspace = true }
sory-utils-template = { workspace = true }
sory-windows-sandbox = { package = "sory-windows-sandbox", path = "../windows-sandbox-rs" }
csv = { workspace = true }
dirs = { workspace = true }
dunce = { workspace = true }
eventsource-stream = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
iana-time-zone = { workspace = true }
image = { workspace = true, features = ["jpeg", "png", "webp"] }
indexmap = { workspace = true }
libc = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex-lite = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
rmcp = { workspace = true, default-features = false, features = [
    "base64",
    "macros",
    "schemars",
    "server",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
shlex = { workspace = true }
similar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
tokio-util = { workspace = true, features = ["rt"] }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true, features = ["log"] }
url = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4", "v5"] }
which = { workspace = true }
whoami = { workspace = true }

# Build OpenSSL from source for musl builds.
[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = { workspace = true, features = ["vendored"] }

# Build OpenSSL from source for musl builds.
[target.aarch64-unknown-linux-musl.dependencies]
openssl-sys = { workspace = true, features = ["vendored"] }

[target.'cfg(unix)'.dependencies]
sory-shell-escalation = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
assert_matches = { workspace = true }
sory-otel = { workspace = true }
sory-test-binary-support = { workspace = true }
sory-utils-cargo-bin = { workspace = true }
core_test_support = { workspace = true }
ctor = { workspace = true }
insta = { workspace = true }
maplit = { workspace = true }
opentelemetry = { workspace = true }
predicates = { workspace = true }
pretty_assertions = { workspace = true }
test-case = "3.3.1"
opentelemetry_sdk = { workspace = true, features = [
    "experimental_metrics_custom_reader",
    "metrics",
] }
serial_test = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-test = { workspace = true, features = ["no-env-filter"] }
walkdir = { workspace = true }
wiremock = { workspace = true }
zstd = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["openssl-sys"]
