pub mod auth;
pub mod auth_env_telemetry;
pub mod token_data;

mod device_code_auth;
mod pkce;
mod server;

pub use device_code_auth::DeviceCode;
pub use device_code_auth::complete_device_code_login;
pub use device_code_auth::request_device_code;
pub use device_code_auth::run_device_code_login;
pub use server::LoginServer;
pub use server::ServerOptions;
pub use server::ShutdownHandle;
pub use server::run_login_server;
pub use sory_client::BuildCustomCaTransportError as BuildLoginHttpClientError;
pub use sory_config::types::AuthCredentialsStoreMode;

pub use auth::AuthConfig;
pub use auth::AuthDotJson;
pub use auth::AuthManager;
pub use auth::AuthManagerConfig;
pub use auth::CLIENT_ID;
pub use auth::SORY_ACCESS_TOKEN_ENV_VAR;
pub use auth::SORY_API_KEY_ENV_VAR;
pub use auth::soryAuth;
pub use auth::ExternalAuth;
pub use auth::ExternalAuthChatgptMetadata;
pub use auth::ExternalAuthRefreshContext;
pub use auth::ExternalAuthRefreshReason;
pub use auth::ExternalAuthTokens;
pub use auth::ALL_PROVIDER_ENV_VARS;
pub use auth::ANTHROPIC_API_KEY_ENV_VAR;
pub use auth::CEREBRAS_API_KEY_ENV_VAR;
pub use auth::COHERE_API_KEY_ENV_VAR;
pub use auth::DEEPINFRA_API_KEY_ENV_VAR;
pub use auth::DEEPSEEK_API_KEY_ENV_VAR;
pub use auth::FIREWORKS_API_KEY_ENV_VAR;
pub use auth::GEMINI_API_KEY_ENV_VAR;
pub use auth::GOOGLE_API_KEY_ENV_VAR;
pub use auth::GROQ_API_KEY_ENV_VAR;
pub use auth::MISTRAL_API_KEY_ENV_VAR;
pub use auth::NVIDIA_API_KEY_ENV_VAR;
pub use auth::OPENAI_API_KEY_ENV_VAR;
pub use auth::OPENROUTER_API_KEY_ENV_VAR;
pub use auth::PERPLEXITY_API_KEY_ENV_VAR;
pub use auth::TOGETHER_API_KEY_ENV_VAR;
pub use auth::XAI_API_KEY_ENV_VAR;
pub use auth::REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::RefreshTokenError;
pub use auth::UnauthorizedRecovery;
pub use auth::default_client;
pub use auth::enforce_login_restrictions;
pub use auth::load_auth_dot_json;
pub use auth::login_with_access_token;
pub use auth::login_with_api_key;
pub use auth::logout;
pub use auth::logout_with_revoke;
pub use auth::read_sory_access_token_from_env;
pub use auth::read_openai_api_key_from_env;
pub use auth::detect_provider_api_key_from_env;
pub use auth::save_auth;
pub use auth_env_telemetry::AuthEnvTelemetry;
pub use auth_env_telemetry::collect_auth_env_telemetry;
pub use token_data::TokenData;
