[package]
name = "sory-install-context"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "sory_install_context"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
sory-utils-home-dir = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
