[package]
name = "sory-sandboxing"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "sory_sandboxing"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
sory-network-proxy = { workspace = true }
sory-protocol = { workspace = true }
sory-utils-absolute-path = { workspace = true }
dunce = { workspace = true }
libc = { workspace = true }
serde_json = { workspace = true }
regex-lite = { workspace = true }
tracing = { workspace = true, features = ["log"] }
url = { workspace = true }
which = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
