[package]
name = "sory-arg0"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "sory_arg0"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
sory-apply-patch = { workspace = true }
sory-exec-server = { workspace = true }
sory-linux-sandbox = { workspace = true }
sory-sandboxing = { workspace = true }
sory-shell-escalation = { workspace = true }
sory-utils-absolute-path = { workspace = true }
sory-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
